---
- name: Update sources
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 86400
    changed_when: false

- name: Install apt-cacher-ng
  ansible.builtin.apt:
    name: apt-cacher-ng
    default_release: "{{ apt_cacher_ng_default_release | default(omit) }}"
    state: present
  become: true
  when: ansible_distribution == 'Ubuntu'
  register: apt_cacher_ng_installed
