---
# tasks file for sorensj.apt-cacher-ng
- name: Setting variables for OS
  ansible.builtin.include_vars: "{{ ansible_os_family }}.yml"

- name: Include install
  ansible.builtin.include_tasks: install_apt_cache.yml
  tags: install
  when: apt_cacher_ng_server is not defined

- name: Include configurations
  ansible.builtin.include_tasks: configure.yml
  tags: configure
  when: apt_cacher_ng_server is not defined

- name: Include client tasks
  ansible.builtin.include_tasks: client.yml
  tags: client
  when: apt_cacher_ng_server is defined
