---
- name: Prepare
  hosts: all
  gather_facts: false
  tasks:
    - name: apt-proxy
      ansible.builtin.copy:
        content: "Acquire::http::Proxy \"{{ lookup('env', 'APT_PROXY') }}\"; Acquire::https::Proxy \"false\";"
        dest: /etc/apt/apt.conf.d/01proxy
      failed_when: false
      changed_when: false
      when: lookup('env', 'APT_PROXY') is defined

    - name: apt-cacher-ng
      apt:
        name: apt-cacher-ng
        state: present
      become: true
      become_user: root
      when: ansible_distribution == 'Ubuntu'

    - name: apt-cacher-ng
      ansible.builtin.service:
        name: apt-cacher-ng
        state: started
        enabled: true
      become: true
      become_user: root
      when: ansible_distribution == 'Ubuntu'

    - name: apt-cacher-ng report page
      uri:
        url: "http:// {{ ansible_default_ipv4.address }}:{{ apt_cacher_ng_port }}/report-page.html"
        status_code: 200
      register: apt_cacher_ng_report_page
      until: apt_cacher_ng_report_page.status == 200
      retries: 10
      delay: 5
      ignore_errors: yes

    - name: debug
      debug:
        var: apt_cacher_ng_report_page
